### PR TITLE
Fix CI/CD build

### PR DESCRIPTION
**Pull request by gkazakov111**

### CODE REVIEW

**Review by ekaneva — DISMISSED** [review]

**Review by ekaneva — COMMENTED** [review]
Ask someone who is a Github admin (e.g. @dbelev) to remove this check `ci/dockercloud` from the project.

**Review by rnov — APPROVED** [review]

**Comment by ekaneva** [comment]
> Ask someone who is a Github admin (e.g. @dbelev) to remove this check `ci/dockercloud` from the project.

Was this done?

**Review by ekaneva — COMMENTED** [review]
Where is this deployed, so we can verify the change is working and not breaking something else?
Since `dev` is not an option, maybe deploy to `staging` then.

**Review by ekaneva — APPROVED** [review]
`build-info` looks good on `stating`, thank you for deploying

Just one thing to note here - your release should not be `2.0.0` as this is not a major change. You should rather go with `1.28.1` as this is a fix. Please keep in mind when deploying. @gkazakov111

**Pull request merged**
