### PR TITLE
Fix/map preview

### PR DESCRIPTION
**Pull request by Nesze**

### CODE REVIEW

**Review by bogdanguranda — APPROVED** [review]
Should the preview query param be added to methode-internal-components-mapper also?

**Comment by Nesze** [comment]
It is.

**Review by radutudor — APPROVED** [review]

**Comment by radutudor** [comment]
Out of curiosity, what's the difference between the map and the content-transform endpoints? Is it just the fact that map does not require the UUID as a path variable?

**Comment by Nesze** [comment]
Yepp, the content-transform is a historical thing, would prefer to remove that completely.
There is a ticket in our trello board to do that.

**Review by kovacshuni — APPROVED** [review]

**Comment by Nesze** [comment]
Tested in `rj` by @GeorgeBoitor.

**Pull request merged**
